use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAvatarLeadsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('avatar_leads', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('agent_id')->unsigned()->nullable();
            $table->integer('lead_id')->nullable();
            $table->text('vendor_id')->nullable();
            $table->bigInteger('list_id')->unsigned()->nullable();
            $table->text('gmt_offset_now')->nullable();
            $table->text('phone_code')->nullable();
            $table->text('smoker')->nullable();
            $table->text('phone_number')->nullable();
            $table->text('title')->nullable();
            $table->text('first_name')->nullable();
            $table->text('fullname')->nullable();
            $table->text('middle_initial')->nullable();
            $table->text('last_name')->nullable();
            $table->text('address1')->nullable();
            $table->text('address2')->nullable();
            $table->text('address3')->nullable();
            $table->text('city')->nullable();
            $table->text('state')->nullable();
            $table->text('province')->nullable();
            $table->text('postal_code')->nullable();
            $table->text('country_code')->nullable();
            $table->text('gender')->nullable();
            $table->text('date_of_birth')->nullable();
            $table->text('alt_phone')->nullable();
            $table->text('email')->nullable();
            $table->text('security_phrase')->nullable();
            $table->text('comments')->nullable();
            $table->text('user')->nullable();
            $table->text('pass')->nullable();
            $table->text('orig_pass')->nullable();
            $table->text('campaign')->nullable();
            $table->text('phone_login')->nullable();
            $table->text('original_phone_login')->nullable();
            $table->text('phone_pass')->nullable();
            $table->text('fronter')->nullable();
            $table->text('closer')->nullable();
            $table->text('group_a')->nullable();
            $table->text('channel_group')->nullable();
            $table->text('SQLdate')->nullable();
            $table->text('epoch')->nullable();
            $table->text('uniqueid')->nullable();
            $table->text('customer_zap_channel')->nullable();
            $table->text('customer_server_ip')->nullable();
            $table->text('server_ip')->nullable();
            $table->text('SIPexten')->nullable();
            $table->text('session_id')->nullable();
            $table->text('phone')->nullable();
            $table->text('parked_by')->nullable();
            $table->text('dispo')->nullable();
            $table->text('dialed_number')->nullable();
            $table->text('dialed_label')->nullable();
            $table->text('source_id')->nullable();
            $table->text('rank')->nullable();
            $table->text('OWNER')->nullable();
            $table->text('camp_script')->nullable();
            $table->text('in_script')->nullable();
            $table->text('in_script_two')->nullable();
            $table->text('agent_name')->nullable();
            $table->text('agent_email')->nullable();
            $table->text('recording_filename')->nullable();
            $table->integer('recording_id')->nullable();
            $table->text('user_custom_one')->nullable();
            $table->text('user_custom_two')->nullable();
            $table->text('user_custom_three')->nullable();
            $table->text('user_custom_four')->nullable();
            $table->text('user_custom_five')->nullable();
            $table->text('preset_number_a')->nullable();
            $table->text('preset_number_b')->nullable();
            $table->text('preset_number_c')->nullable();
            $table->text('preset_number_d')->nullable();
            $table->text('preset_number_e')->nullable();
            $table->text('preset_dtmf_a')->nullable();
            $table->text('preset_dtmf_b')->nullable();
            $table->text('did_id')->nullable();
            $table->text('did_extension')->nullable();
            $table->text('did_pattern')->nullable();
            $table->text('did_description')->nullable();
            $table->text('closecallid')->nullable();
            $table->text('xfercallid')->nullable();
            $table->text('agent_log_id')->nullable();
            $table->text('entry_list_id')->nullable();
            $table->text('call_id')->nullable();
            $table->text('user_group')->nullable();
            $table->text('list_name')->nullable();
            $table->text('list_description')->nullable();
            $table->text('entry_date')->nullable();
            $table->text('did_custom_one')->nullable();
            $table->text('did_custom_two')->nullable();
            $table->text('did_custom_three')->nullable();
            $table->text('did_custom_four')->nullable();
            $table->text('did_custom_five')->nullable();
            $table->text('called_count')->nullable();
            $table->text('session_name')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->text('age')->nullable();
            $table->text('verifier_name')->nullable();
            $table->text('dailer_no')->nullable();
            $table->text('center')->nullable();
            $table->text('closer_name')->nullable();
            $table->text('xferSubmission')->nullable();
            $table->text('recording_link')->nullable();
            $table->text('script_width')->nullable();
            $table->text('script_height')->nullable();
            $table->text('email_row_id')->nullable();
            $table->text('INOUT')->nullable();
            $table->text('LOGINvarONE')->nullable();
            $table->text('LOGINvarTWO')->nullable();
            $table->text('LOGINvarTHREE')->nullable();
            $table->text('LOGINvarFOUR')->nullable();
            $table->text('LOGINvarFIVE')->nullable();
            $table->text('hide_relogin_fields')->nullable();
            $table->text('web_vars')->nullable();
            $table->text('dialername')->nullable();
            $table->text('centername')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('avatar_leads');
    }
}
